#!/usr/bin/env python3
"""
text_extractor.py
==================
Pulls plain text out of a .txt, .docx, or .pdf file, so it can be fed
into the handwriting pipeline (handwriting_ebb.py).

Usage as a library:
    from text_extractor import extract_text
    text = extract_text("myfile.docx")

Usage standalone (just to preview what would be extracted):
    python3 text_extractor.py myfile.pdf
"""

import argparse
import os
import sys


def extract_text(path):
    """Return the plain text content of a .txt, .docx, or .pdf file."""
    ext = os.path.splitext(path)[1].lower()

    if ext == ".txt":
        return _extract_txt(path)
    elif ext == ".docx":
        return _extract_docx(path)
    elif ext == ".pdf":
        return _extract_pdf(path)
    else:
        raise ValueError(
            f"Unsupported file type '{ext}'. Supported: .txt, .docx, .pdf"
        )


def _extract_txt(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def _extract_docx(path):
    import docx  # python-docx

    doc = docx.Document(path)
    parts = []

    # Paragraphs, in document order, preserving blank lines between them.
    for para in doc.paragraphs:
        parts.append(para.text)

    # Also pull text out of any tables (python-docx doesn't include table
    # text in doc.paragraphs).
    for table in doc.tables:
        for row in table.rows:
            row_text = "\t".join(cell.text for cell in row.cells)
            if row_text.strip():
                parts.append(row_text)

    return "\n".join(parts)


def _extract_pdf(path):
    from pypdf import PdfReader

    reader = PdfReader(path)
    parts = []
    for page in reader.pages:
        page_text = page.extract_text() or ""
        parts.append(page_text)
    return "\n".join(parts)


def clean_text(text, collapse_blank_lines=True):
    """
    Light cleanup pass: normalize whitespace, strip trailing spaces per line,
    optionally collapse runs of multiple blank lines down to one.
    """
    lines = [line.rstrip() for line in text.splitlines()]
    if collapse_blank_lines:
        cleaned = []
        prev_blank = False
        for line in lines:
            is_blank = (line.strip() == "")
            if is_blank and prev_blank:
                continue
            cleaned.append(line)
            prev_blank = is_blank
        lines = cleaned
    return "\n".join(lines).strip()


# --------------------------------------------------------------------------
# Structure-aware extraction: headings, bullets, numbered lists, paragraphs
# --------------------------------------------------------------------------
#
# Each block is a dict:
#   {"type": "heading" | "bullet" | "numbered" | "paragraph" | "blank",
#    "text": str,       # the content, marker/bullet char already stripped
#    "level": int}       # heading level (1=biggest), or list indent level
#
# This lets the handwriting generator render headings bigger, indent and
# bullet/number list items, and preserve paragraph breaks -- rather than
# flattening everything into one undifferentiated block of text.

_BULLET_RE = None
_NUMBERED_RE = None


def _get_patterns():
    global _BULLET_RE, _NUMBERED_RE
    import re
    if _BULLET_RE is None:
        _BULLET_RE = re.compile(r"^[\u2022\u25CF\u25E6\-\*]\s+(.*)")
        _NUMBERED_RE = re.compile(r"^(\d+)[\.\)]\s+(.*)")
    return _BULLET_RE, _NUMBERED_RE


def extract_blocks(path):
    """Return a list of structured blocks for the given .txt/.docx/.pdf file."""
    ext = os.path.splitext(path)[1].lower()
    if ext == ".docx":
        return _extract_docx_blocks(path)
    elif ext == ".pdf":
        return _extract_pdf_blocks(path)
    elif ext == ".txt":
        return _extract_line_heuristic_blocks(_extract_txt(path))
    else:
        raise ValueError(f"Unsupported file type '{ext}'. Supported: .txt, .docx, .pdf")


def _get_numbering_formats(doc):
    """
    Parse the document's numbering definitions (numbering.xml) into
    {numId: {ilvl: numFmt}}. This is needed because modern Word list
    creation (clicking the bullet/numbering toolbar buttons) applies direct
    numPr formatting under the generic "List Paragraph" style -- it does NOT
    use the legacy "List Bullet"/"List Number" named styles, and the actual
    bullet character or number is never present in paragraph.text (it's
    auto-generated by the numbering definition, not literal text). So the
    only reliable way to tell a real bullet list from a real numbered list
    is to look up its numFmt ("bullet" vs "decimal"/"lowerRoman"/etc.) here.
    """
    from docx.oxml.ns import qn

    try:
        numbering_part = doc.part.numbering_part
    except Exception:
        return {}
    if numbering_part is None:
        return {}

    root = numbering_part.element

    abstract_formats = {}
    for abstract_num in root.findall(qn("w:abstractNum")):
        abstract_id = abstract_num.get(qn("w:abstractNumId"))
        lvl_formats = {}
        for lvl in abstract_num.findall(qn("w:lvl")):
            ilvl = lvl.get(qn("w:ilvl"))
            fmt_el = lvl.find(qn("w:numFmt"))
            lvl_formats[ilvl] = fmt_el.get(qn("w:val")) if fmt_el is not None else None
        abstract_formats[abstract_id] = lvl_formats

    num_to_abstract = {}
    for num in root.findall(qn("w:num")):
        num_id = num.get(qn("w:numId"))
        abstract_id_el = num.find(qn("w:abstractNumId"))
        if abstract_id_el is not None:
            num_to_abstract[num_id] = abstract_id_el.get(qn("w:val"))

    return {
        num_id: abstract_formats.get(abstract_id, {})
        for num_id, abstract_id in num_to_abstract.items()
    }


_BULLET_NUMFMTS = {"bullet"}
_NUMBERED_NUMFMTS = {
    "decimal", "decimalZero", "lowerRoman", "upperRoman",
    "lowerLetter", "upperLetter", "ordinal", "cardinalText", "ordinalText",
}


def _paragraph_list_type(para, numbering_formats):
    """Returns 'bullet', 'numbered', or None based on the paragraph's actual
    numPr numFmt (not just style name -- see _get_numbering_formats)."""
    from docx.oxml.ns import qn

    pPr = para._p.pPr
    if pPr is None or pPr.numPr is None:
        return None
    numId_el = pPr.numPr.find(qn("w:numId"))
    ilvl_el = pPr.numPr.find(qn("w:ilvl"))
    if numId_el is None:
        return None
    num_id = numId_el.get(qn("w:val"))
    ilvl = ilvl_el.get(qn("w:val")) if ilvl_el is not None else "0"

    fmt = numbering_formats.get(num_id, {}).get(ilvl)
    if fmt in _BULLET_NUMFMTS:
        return "bullet"
    if fmt in _NUMBERED_NUMFMTS:
        return "numbered"
    return None


def _extract_docx_blocks(path):
    import docx

    doc = docx.Document(path)
    numbering_formats = _get_numbering_formats(doc)
    blocks = []

    for para in doc.paragraphs:
        text = para.text.strip()
        style = (para.style.name or "") if para.style else ""

        if not text:
            blocks.append({"type": "blank", "text": "", "level": 0})
            continue

        if style.startswith("Heading") or style.startswith("Title"):
            # "Heading 1", "Heading 2", ... -> level number; "Title" -> level 1
            digits = "".join(ch for ch in style if ch.isdigit())
            level = int(digits) if digits else 1
            blocks.append({"type": "heading", "text": text, "level": level})
            continue

        # Check the ACTUAL numbering format first (handles modern
        # toolbar-created lists correctly) before falling back to legacy
        # style-name matching for older/manually-styled documents.
        list_type = _paragraph_list_type(para, numbering_formats)
        if list_type == "bullet":
            blocks.append({"type": "bullet", "text": text, "level": 0})
        elif list_type == "numbered":
            blocks.append({"type": "numbered", "text": text, "level": 0})
        elif "List Bullet" in style:
            blocks.append({"type": "bullet", "text": text, "level": 0})
        elif "List Number" in style:
            blocks.append({"type": "numbered", "text": text, "level": 0})
        else:
            blocks.append({"type": "paragraph", "text": text, "level": 0})

    for table in doc.tables:
        for row in table.rows:
            row_text = " | ".join(cell.text.strip() for cell in row.cells)
            if row_text.strip():
                blocks.append({"type": "paragraph", "text": row_text, "level": 0})

    return blocks


def _looks_like_bullet_xml(para):
    """Best-effort check for Word's numbering/bullet property on a paragraph.
    Superseded by _paragraph_list_type() which properly distinguishes bullet
    vs numbered by inspecting the actual numFmt -- kept unused/dead only if
    something external still imports it; safe to ignore otherwise."""
    try:
        pPr = para._p.pPr
        return pPr is not None and pPr.numPr is not None
    except Exception:
        return False


def _chars_to_line_text(chars):
    """
    Join a line's worth of pdfplumber char dicts into text, inserting a space
    wherever there's a horizontal gap between characters -- without this,
    words with no explicit space glyph in the PDF's content stream (common
    with many real-world PDF generators/exports) get silently concatenated
    into one unbroken string.
    """
    if not chars:
        return ""
    chars = sorted(chars, key=lambda c: c["x0"])
    parts = [chars[0]["text"]]
    for prev, cur in zip(chars, chars[1:]):
        gap = cur["x0"] - prev["x1"]
        # A gap wider than ~a quarter of the character's own height is a
        # reasonable signal of a word boundary that had no explicit space
        # glyph. (Normal inter-letter kerning gaps are much smaller than this.)
        char_height = max(prev.get("height", 1), 1)
        if gap > char_height * 0.25 and not cur["text"].isspace() and not prev["text"].isspace():
            parts.append(" ")
        parts.append(cur["text"])
    return "".join(parts)


def _extract_pdf_blocks(path):
    import pdfplumber

    all_sizes = []
    lines_with_size = []  # (text, median_char_size)

    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            chars = page.chars
            if not chars:
                # No character-level data (likely scanned/raster) -- fall back
                # to plain text extraction for this page with no size info.
                text = page.extract_text() or ""
                for line in text.splitlines():
                    lines_with_size.append((line, None))
                continue

            # Group chars into lines by their 'top' (y) position.
            chars_sorted = sorted(chars, key=lambda c: (round(c["top"], 1), c["x0"]))
            current_top = None
            current_line_chars = []
            for c in chars_sorted:
                top = round(c["top"], 1)
                if current_top is None or abs(top - current_top) > 2:
                    if current_line_chars:
                        line_text = _chars_to_line_text(current_line_chars).strip()
                        sizes = [ch["size"] for ch in current_line_chars]
                        median_size = sorted(sizes)[len(sizes) // 2]
                        lines_with_size.append((line_text, median_size))
                        all_sizes.extend(sizes)
                    current_line_chars = [c]
                    current_top = top
                else:
                    current_line_chars.append(c)
            if current_line_chars:
                line_text = _chars_to_line_text(current_line_chars).strip()
                sizes = [ch["size"] for ch in current_line_chars]
                median_size = sorted(sizes)[len(sizes) // 2]
                lines_with_size.append((line_text, median_size))
                all_sizes.extend(sizes)

    body_size = sorted(all_sizes)[len(all_sizes) // 2] if all_sizes else None

    blocks = []
    bullet_re, numbered_re = _get_patterns()
    for line, size in lines_with_size:
        text = line.strip()
        if not text:
            blocks.append({"type": "blank", "text": "", "level": 0})
            continue

        m = bullet_re.match(text)
        if m:
            blocks.append({"type": "bullet", "text": m.group(1), "level": 0})
            continue
        m = numbered_re.match(text)
        if m:
            blocks.append({"type": "numbered", "text": m.group(2), "level": 0})
            continue

        if size is not None and body_size is not None and size > body_size * 1.2:
            level = 1 if size > body_size * 1.4 else 2
            blocks.append({"type": "heading", "text": text, "level": level})
        else:
            blocks.append({"type": "paragraph", "text": text, "level": 0})

    return blocks


def _extract_line_heuristic_blocks(raw_text):
    """For plain .txt (no styling info at all): detect bullets/numbers by
    leading characters, blank lines as paragraph breaks, everything else
    as plain paragraph text. No heading detection is possible without
    font-size information."""
    bullet_re, numbered_re = _get_patterns()
    blocks = []
    for line in raw_text.splitlines():
        text = line.strip()
        if not text:
            blocks.append({"type": "blank", "text": "", "level": 0})
            continue
        m = bullet_re.match(text)
        if m:
            blocks.append({"type": "bullet", "text": m.group(1), "level": 0})
            continue
        m = numbered_re.match(text)
        if m:
            blocks.append({"type": "numbered", "text": m.group(2), "level": 0})
            continue
        blocks.append({"type": "paragraph", "text": text, "level": 0})
    return blocks


def main():
    p = argparse.ArgumentParser(description="Extract plain text from .txt/.docx/.pdf files.")
    p.add_argument("path", help="Path to the .txt, .docx, or .pdf file.")
    p.add_argument("-o", "--output", help="Optional: write extracted text to this file instead of stdout.")
    p.add_argument("--no-clean", action="store_true", help="Skip whitespace cleanup pass.")
    p.add_argument("--blocks", action="store_true",
                    help="Show structured block extraction (headings/bullets/paragraphs) instead of flat text.")
    args = p.parse_args()

    if args.blocks:
        try:
            blocks = extract_blocks(args.path)
        except Exception as e:
            print(f"[error] failed to extract blocks from '{args.path}': {e}", file=sys.stderr)
            sys.exit(1)
        for b in blocks:
            print(f"[{b['type']:9s} lvl={b['level']}] {b['text']}")
        return

    try:
        raw = extract_text(args.path)
    except Exception as e:
        print(f"[error] failed to extract text from '{args.path}': {e}", file=sys.stderr)
        sys.exit(1)

    text = raw if args.no_clean else clean_text(raw)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"[info] wrote extracted text to {args.output} ({len(text)} characters)")
    else:
        print(text)


if __name__ == "__main__":
    main()